travis:
  secure:
    BINSTAR_TOKEN: QNQNVlZszrvgTVF9KDAxHqJjVG24RZVkHK9GLHHXF0UQwaNUYw2gY71KnYGeJ6JVYJG0309KF+5sva8kPiu9uRgZLyeuUIo2HIjnjj09ROxIzzssMcjh/7UFeFb/CVEUyr+7JWrrQ6GYRw9vcTO84Ha6nPa0IXWQsDawTzmCcQWyOFZudIE5vwZfH8xW/JzemS90TlGIbPOhLwdk3RiniAzX2IOhlla1R0FnDJgfm+0IEMGxP57ieATLEb03QMp7eI52kkeXxSKASEEImu+qoX2VAApwZJeG8MaHK8RvrbN+J2mzB8VXF+pUxD9cIBnQUWrx+Xlc84IMgh7m+oAXI81VyIafLprX4gfQ2ebl9zwd/hDaIcz3QJWBpbZ3NZp75h3Qex0P6CLxMsNkA5XUZaQtuW5K9b2m/8Eg048zJ9Vqq/FIe0n9tGRYyuknLQqxpS8YapvNphKWour399Vau9SiZygit3OJmkrOaBNvydKFfl/zdK+fCKI+hWYBMs8J8feFzZa5aULZV8XCxFR+lSFBzTvidoOkPkA2tmttjB9WWczdiwkRrzh193DoYWVMVehzEDxD5ltQtRtKMJbFgd/gfB6OjerfvSlULdcVG3DM+8UoO7Xehv3u5nlxtnitRMWJvIMt/9MnN6zXMdoiB7q3LXYNtDAjg8lx6o1Mq6g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
