travis:
  secure:
    BINSTAR_TOKEN: W23lSbZxjCkr7fWu44Gq7MDH3zMHdrkF9dMjzoWUUik5yrhjd+/WBP00yS5WEoLOrxXTEoqdF0ArbTTyxyFXsglOPnzNNitijOFECdau9SFsc9QRCUL5KAeVXcZ74We27BGAy+e1DTkX/rbAvsvLW71QzG5lJctq1mhmf5j7pe6VLTYGxOVkntKH0j51GNC/UPaZKal9vx8kFOJJB0eczQVhCARI9bLmzK/BPqrsGtbGW8LLoiGFsQlwiJRwUJDUun4CNZMJB6n/Uf77aAUtW8ouKQDZANjVwayqIyazzDHO6AyB4e8OSWSLbykPZnHL+nnsxrj/WQlO5NdxmHbk9M8ntAo1cK3fzxpXSkn5mnrUU2AXpyy65HY1rhMe2ds0t/1gvomEEGDfybCW8iJaxO2XMI3k+UzIgtWI7n0c3WINuSF+EsdaFfxoY7byLXTELq3d2lYQ2OxXcG5nWe4gZdLGE7puJgOt8CNsIEtSsVCTMyuLsGp/h7EjSzhHonuv7USGmmGEa5+C6wBhizk+knhkJFthl0Iu2vKb0ICIWHb2y+0fi6X99txiWPVma2sVNlffepzhlB9+oClIaLJU4iau8avTIKceYlGZM+38ZU62yjZtwgO9UFZ5DM6oEQ74eX53DsfL5Z0lcuApRn2fTMPwcHKnudUFk8cB0DrIs9w=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
